MobileStore/Controllers/ShopPageController.cs
using Models.ViewModels;
using Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobileStore.Controllers
{
    public class ShopPageController : Controller
    {
        private MobileStoreContext db = new MobileStoreContext();
        // GET: ShopPage
        public ActionResult Index(string productType, string sortOrder,string brand, string currentFilter, string searchString, int? page)
        {
            

            
            int productTypeId = db.ProductTypes.Where(m => m.ProductTypeName == productType).Select(m=>m.ProductTypeId).FirstOrDefault();
            ViewBag.ProductTypeName = productType;
            ViewBag.ProductTypeId = productTypeId;

            List<ProductShop> listPrd= new List<ProductShop>();

            //--Create a list to show Product Shop List
            if (productType != null)
            {
                foreach (var item in db.Products.Where(m => m.ProductTypeId == productTypeId))
                {

                    var prdId = item.ProductId ;
                    ProductShop productShop = new ProductShop();
                    Nullable<decimal> PriceCheapestType = Decimal.MaxValue;
                    int count = 0;

                    //Find branch cheapest in Product to show page shop, Sale marketting
                    if (productType == "Smartphone")
                    {
                        //Search in PortableDevice by product id
                        foreach (var item1 in db.ProductPortableDevices.Where(m => m.ProductId == prdId))
                        {
                            if (item1.Price < PriceCheapestType)
                            {
                                PriceCheapestType = item1.Price;
                            }
                            //Check Quantiny this product to show nofication
                            count += item1.Quantiny;
                        }
                    }
                    else if (productType == "Accessory")
                    {
                        //Search in AccessoryDevice by product id
                            foreach (var item1 in db.ProductAccessories.Where(m => m.ProductId == prdId))
                            {
                                if (item1.Price < PriceCheapestType)
                                {
                                    PriceCheapestType = item1.Price;
                                }
                                count += item1.Quantiny;
                            }
                            
                    }

                    //Assign variable Price Cheapest branch
                    if (productType == "Smartphone")
                    {
                        //Search in PortableDevice by product id
                        foreach (var item1 in db.ProductPortableDevices.Where(m => m.ProductId == prdId))
                        {
                            if (item1.Price == PriceCheapestType)
                            {
                                productShop.CheapestProductId = item1.ProductPortableDeviceId;
                            }
                        }
                    }
                    else if (productType == "Accessory")
                    {
                        //Search in AccessoryDevice by product id
                            foreach (var item1 in db.ProductAccessories.Where(m => m.ProductId == prdId))
                            {
                                if (item1.Price == PriceCheapestType)
                                {
                                productShop.CheapestProductId = item1.ProductAccessoryId;
                                }
                            }
                    }

                    productShop.ProductId = prdId;
                    productShop.ProductName = item.ProductName;
                    productShop.RealeaseDate = item.RealeaseDate;
                    productShop.FileImage = item.FileImage;
                    productShop.PriceCheapestType = PriceCheapestType;
                    productShop.Brand = db.BrandTypes.Where(m=>m.BrandTypeId==item.BrandTypeId).Select(m=>m.BrandName).FirstOrDefault();
                    if (count == 0)
                    {
                        productShop.Stocking = false;
                    }
                    listPrd.Add(productShop);
                }
            }
            //----------------------------------------

            ViewBag.CountProduct = listPrd.Count();
            ViewBag.ProductType = productType;
            ViewBag.BrandList = listPrd.Select(m => m.Brand).Distinct();

            //Paging, sorting part
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                listPrd = listPrd.Where(s => s.ProductName.Contains(searchString)).ToList();
            }

            if (!String.IsNullOrEmpty(brand))
            {
                listPrd = listPrd.Where(m => m.Brand == brand).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    listPrd = listPrd.OrderByDescending(s => s.ProductName).ToList();
                    break;
                case "Date":
                    listPrd = listPrd.OrderBy(s => s.RealeaseDate).ToList();
                    break;
                case "date_desc":
                    listPrd = listPrd.OrderByDescending(s => s.RealeaseDate).ToList();
                    break;
                default:
                    listPrd = listPrd.OrderBy(s => s.ProductName).ToList();
                    break;
            }
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(listPrd.ToPagedList(pageNumber, pageSize));
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MobileStore/Controllers/ShoppingCartController.cs
using Models.ViewModels;
using Models.EF;
using Models.Bus;

using MobileStore.Common;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace MobileStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private MobileStoreContext db = new MobileStoreContext();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            List<ShoppingCartItemBrowser> list = null;
            if (Session["shoppingcart"] == null)
            {

                list = new List<ShoppingCartItemBrowser>();
            }
            else
            {

                list = (List<ShoppingCartItemBrowser>)Session["shoppingcart"];
                ViewBag.TotalPrice = list.Sum(m => m.Price * m.Quantiny);
            }
            var sessionUser = (LoginModelDisplay)Session["USER_SESSION"];
            ViewBag.ListAddress = db.AddressMembers.Where(m => m.MemberId == sessionUser.MemberAccountId);
            return View(list);
        }
        public ActionResult AddItem(int productTypeId, int currentProductDetailId, int? ram, int? memory, string color, decimal price, int quantity,int productId)
        {
            FormatBus format = new FormatBus();
            
            string productType = db.ProductTypes.Where(m => m.ProductTypeId == productTypeId).Select(m => m.ProductTypeName).FirstOrDefault();
            string nameProduct = db.Products.Where(m => m.ProductId == productId).Select(m => m.ProductName).FirstOrDefault();

            ViewBag.ProductId = productId;
            ViewBag.ProductType = productType;


            if (Session["shoppingcart"] == null)
            {
                List<ShoppingCartItemBrowser> listShoppingCart = new List<ShoppingCartItemBrowser>();
                if (productType == "Smartphone")
                {
                    string fileImage = "/Assets/user/images/" + productType + "/" + productId + "-" + color + "-1.jpg";
                    ShoppingCartItemBrowser item = new ShoppingCartItemBrowser { ProductDetailId = currentProductDetailId, ProductId=productId, Name= nameProduct, RamSize = ram, MemorySize = memory, Color = color, Price = price, FileImage=fileImage, Quantiny = quantity, ProductTypeName=productType};
                    listShoppingCart.Add(item);
                }
                else if (productType == "Accessory")
                {
                    string fileImage = "/Assets/user/images/" + productType + "/" + productId + "-" + color + "-1.jpg";
                    ShoppingCartItemBrowser item = new ShoppingCartItemBrowser { ProductDetailId = currentProductDetailId, ProductId = productId, Name = nameProduct, Color = format.ColorFormat(color), Price = price, FileImage = fileImage, Quantiny = quantity, ProductTypeName = productType };
                    listShoppingCart.Add(item);
                }
                Session["shoppingcart"] = listShoppingCart;

            }
            else
            {
                List<ShoppingCartItemBrowser> listShoppingCart = (List<ShoppingCartItemBrowser>)Session["shoppingcart"];
                if (productType == "Smartphone")
                {
                    if (listShoppingCart.Find(m => m.ProductDetailId == currentProductDetailId) == null)
                    {
                        string fileImage = "/Assets/user/images/" + productType + "/" + productId + "-" + color + "-1.jpg";
                        ShoppingCartItemBrowser item = new ShoppingCartItemBrowser { ProductDetailId = currentProductDetailId, ProductId = productId, Name = nameProduct, RamSize = ram, MemorySize = memory, Color = format.ColorFormat(color), Price = price, Quantiny=1, FileImage = fileImage, ProductTypeName = productType };
                        listShoppingCart.Add(item);
                    }
                    else
                    {
                        foreach (var item in listShoppingCart)
                        {
                            if (item.ProductDetailId == currentProductDetailId)
                            {
                                item.Quantiny += quantity;
                            }
                        }
                    }

                }
                else if (productType == "Accessory")
                {
                    if (listShoppingCart.Find(m => m.ProductDetailId == currentProductDetailId) == null)
                    {
                        string fileImage = "/Assets/user/images/" + productType + "/" + productId + "-" + color + "-1.jpg";
                        ShoppingCartItemBrowser item = new ShoppingCartItemBrowser { ProductDetailId = currentProductDetailId, ProductId = productId, Name = nameProduct, Color = color, Price = price, Quantiny = 1, FileImage = fileImage, ProductTypeName = productType };
                        listShoppingCart.Add(item);
                    }
                    else
                    {
                        foreach (var item in listShoppingCart)
                        {
                            if (item.ProductDetailId == currentProductDetailId)
                            {
                                item.Quantiny += quantity;
                            }
                        }
                    }
                }
                Session["shoppingcart"] = listShoppingCart;
            }

            return RedirectToAction("Index");
        }

        public JsonResult UpdateCart(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<JsonCart>>(cartModel);
            var sessionCart= (List<ShoppingCartItemBrowser>)Session["shoppingcart"];
            foreach(var item in sessionCart)
            {
                var itemIdSession = item.ProductId.ToString()+"-"+ item.ProductDetailId.ToString();
                var jsonItem = jsonCart.SingleOrDefault(x => x.ItemId == itemIdSession);
                if (jsonItem!=null &&jsonItem.Quantity>0)
                {
                    item.Quantiny = jsonItem.Quantity;
                }
                else if (jsonItem.Quantity == 0)
                {
                    sessionCart.RemoveAll(m => m.ProductDetailId == item.ProductDetailId);
                }
            }
            Session["shoppingcart"] = sessionCart;
            return Json(new
            {
                status = true
            });
        }

        public JsonResult DeleteItem(string itemId)
        {
            var sessionCart = (List<ShoppingCartItemBrowser>)Session["shoppingcart"];
            sessionCart.RemoveAll(x => x.ProductId.ToString() + "-" + x.ProductDetailId.ToString() == itemId);
            Session["shoppingcart"] = sessionCart;
            
            if (sessionCart.Where(x => x.ProductId.ToString() + "-" + x.ProductDetailId.ToString() == itemId).FirstOrDefault() != null)
            {
                return Json(new
                {
                    status = false
                });
            }
            return Json(new
            {
                status = true
            });
        }

        public ActionResult CheckItOut()
        {
            var sessionUser = (LoginModelDisplay)Session["USER_SESSION"];
            if (sessionUser == null)
            {
                return RedirectToAction("Login", "Accounts", new { area = "Admin" });
            }
            db.ShoppingCarts.Add(new ShoppingCart { CustomerId=sessionUser.MemberAccountId, OrderDate = DateTime.Now, StatusCart = 0 });
            int shoppingCartId = db.ShoppingCarts.OrderByDescending(m => m.ShoppingCartId).Select(m=>m.ShoppingCartId).FirstOrDefault();
            var sessionCart = (List<ShoppingCartItemBrowser>)Session["shoppingcart"];
            foreach(var item in sessionCart)
            {
                if (item.ProductTypeName == "Smartphone")
                {
                    db.ShoppingCartItems.Add(new ShoppingCartItem { ShoppingCartId = shoppingCartId, ProductPortableDeviceId = item.ProductDetailId, Quantiny = item.Quantiny, Price = item.Price });

                }
                else if (item.ProductTypeName == "Accessory")
                {
                    db.ShoppingCartItems.Add(new ShoppingCartItem { ShoppingCartId = shoppingCartId, ProductAccessoryId = item.ProductDetailId, Quantiny = item.Quantiny, Price = item.Price });
                }
            }
            db.SaveChanges();
            Session["shoppingcart"] = null;
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

MobileStore/Views/Shared/_AllColorProduct.cshtml
@using Models.Bus;
@{
    FormatBus format = new FormatBus();
    foreach (var item in ViewBag.AllColorProduct)
    {
        <li class="color"><a href="#" title="@item" style="background : @format.ColorFormat(@item);"></a></li>
    }
}

MobileStore/Views/Shared/_BranchSlider.cshtml
<!-- Brands -->

<div class="brands">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="brands_slider_container">

                    <!-- Brands Slider -->

                    <div class="owl-carousel owl-theme brands_slider">

                        <div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="/Assets/user/images/brands_1.jpg" alt=""></div></div>
                        <div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="/Assets/user/images/brands_2.jpg" alt=""></div></div>
                        <div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="/Assets/user/images/brands_3.jpg" alt=""></div></div>
                        <div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="/Assets/user/images/brands_4.jpg" alt=""></div></div>
                        <div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="/Assets/user/images/brands_5.jpg" alt=""></div></div>
                        <div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="/Assets/user/images/brands_6.jpg" alt=""></div></div>
                        <div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="/Assets/user/images/brands_7.jpg" alt=""></div></div>
                        <div class="owl-item"><div class="brands_item d-flex flex-column justify-content-center"><img src="/Assets/user/images/brands_8.jpg" alt=""></div></div>

                    </div>

                    <!-- Brands Slider Navigation -->
                    <div class="brands_nav brands_prev"><i class="fas fa-chevron-left"></i></div>
                    <div class="brands_nav brands_next"><i class="fas fa-chevron-right"></i></div>

                </div>
            </div>
        </div>
    </div>
</div>

MobileStore/Views/Shared/_Categories.cshtml
<ul class="cat_menu">
    @foreach (var item in ViewBag.Categories)
    {
        <li class="hassubs">
            <a href="@Url.Action("Index","ShopPage",new { productType=@item.ProductTypeName})">@item.ProductTypeName<i class="fas fa-chevron-right"></i></a>
            <ul>
                @foreach (var item2 in item.ListBrandName)
                {
                    <li><a href="@Url.Action("Index","ShopPage",new { productType=@item.ProductTypeName,brand=item2})">@item2</a></li>
                }
            </ul>
        </li>
    }
</ul>

MobileStore/Views/Shared/_HeaderCart.cshtml
 <!-- Cart -->
<div class="cart">
    <div class="cart_container d-flex flex-row align-items-center justify-content-end">
        <div class="cart_icon">
            <img src="/Assets/user/images/cart.png" alt="">
            <div class="cart_count"><span>@ViewBag.CountItem</span></div>
        </div>
        <div class="cart_content">
            <div class="cart_text"><a href="@Url.Action("Index","ShoppingCart")">Cart</a></div>
            <div class="cart_price">@ViewBag.SumPrice</div>
        </div>
    </div>
</div>

MobileStore/Views/Shared/_ProductType.cshtml
        @foreach (var item in ViewBag.ProductType)
        {
            <li><a class="clc" href="#">@item</a></li>
        }

MobileStore/Views/Shared/_RecentlyView.cshtml
        <!-- Recently Viewed -->

        <div class="viewed">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="viewed_title_container">
                            <h3 class="viewed_title">Recently Viewed</h3>
                            <div class="viewed_nav_container">
                                <div class="viewed_nav viewed_prev"><i class="fas fa-chevron-left"></i></div>
                                <div class="viewed_nav viewed_next"><i class="fas fa-chevron-right"></i></div>
                            </div>
                        </div>

                        <div class="viewed_slider_container">

                            <!-- Recently Viewed Slider -->

                            <div class="owl-carousel owl-theme viewed_slider">

                                <!-- Recently Viewed Item -->
                                <div class="owl-item">
                                    <div class="viewed_item discount d-flex flex-column align-items-center justify-content-center text-center">
                                        <div class="viewed_image"><img src="/Assets/user/images/view_1.jpg" alt=""></div>
                                        <div class="viewed_content text-center">
                                            <div class="viewed_price">$225<span>$300</span></div>
                                            <div class="viewed_name"><a href="#">Beoplay H7</a></div>
                                        </div>
                                        <ul class="item_marks">
                                            <li class="item_mark item_discount">-25%</li>
                                            <li class="item_mark item_new">new</li>
                                        </ul>
                                    </div>
                                </div>

                                <!-- Recently Viewed Item -->
                                <div class="owl-item">
                                    <div class="viewed_item d-flex flex-column align-items-center justify-content-center text-center">
                                        <div class="viewed_image"><img src="/Assets/user/images/view_2.jpg" alt=""></div>
                                        <div class="viewed_content text-center">
                                            <div class="viewed_price">$379</div>
                                            <div class="viewed_name"><a href="#">LUNA Smartphone</a></div>
                                        </div>
                                        <ul class="item_marks">
                                            <li class="item_mark item_discount">-25%</li>
                                            <li class="item_mark item_new">new</li>
                                        </ul>
                                    </div>
                                </div>

                                <!-- Recently Viewed Item -->
                                <div class="owl-item">
                                    <div class="viewed_item d-flex flex-column align-items-center justify-content-center text-center">
                                        <div class="viewed_image"><img src="/Assets/user/images/view_3.jpg" alt=""></div>
                                        <div class="viewed_content text-center">
                                            <div class="viewed_price">$225</div>
                                            <div class="viewed_name"><a href="#">Samsung J730F...</a></div>
                                        </div>
                                        <ul class="item_marks">
                                            <li class="item_mark item_discount">-25%</li>
                                            <li class="item_mark item_new">new</li>
                                        </ul>
                                    </div>
                                </div>

                                <!-- Recently Viewed Item -->
                                <div class="owl-item">
                                    <div class="viewed_item is_new d-flex flex-column align-items-center justify-content-center text-center">
                                        <div class="viewed_image"><img src="/Assets/user/images/view_4.jpg" alt=""></div>
                                        <div class="viewed_content text-center">
                                            <div class="viewed_price">$379</div>
                                            <div class="viewed_name"><a href="#">Huawei MediaPad...</a></div>
                                        </div>
                                        <ul class="item_marks">
                                            <li class="item_mark item_discount">-25%</li>
                                            <li class="item_mark item_new">new</li>
                                        </ul>
                                    </div>
                                </div>

                                <!-- Recently Viewed Item -->
                                <div class="owl-item">
                                    <div class="viewed_item discount d-flex flex-column align-items-center justify-content-center text-center">
                                        <div class="viewed_image"><img src="/Assets/user/images/view_5.jpg" alt=""></div>
                                        <div class="viewed_content text-center">
                                            <div class="viewed_price">$225<span>$300</span></div>
                                            <div class="viewed_name"><a href="#">Sony PS4 Slim</a></div>
                                        </div>
                                        <ul class="item_marks">
                                            <li class="item_mark item_discount">-25%</li>
                                            <li class="item_mark item_new">new</li>
                                        </ul>
                                    </div>
                                </div>

                                <!-- Recently Viewed Item -->
                                <div class="owl-item">
                                    <div class="viewed_item d-flex flex-column align-items-center justify-content-center text-center">
                                        <div class="viewed_image"><img src="/Assets/user/images/view_6.jpg" alt=""></div>
                                        <div class="viewed_content text-center">
                                            <div class="viewed_price">$375</div>
                                            <div class="viewed_name"><a href="#">Speedlink...</a></div>
                                        </div>
                                        <ul class="item_marks">
                                            <li class="item_mark item_discount">-25%</li>
                                            <li class="item_mark item_new">new</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

MobileStore/Views/Shared/_TopbarUser.cshtml
<div class="top_bar_user">
    <div class="user_icon"><img src="/Assets/user/images/user.svg" alt=""></div>
    @{
        if (@ViewBag.DisplayUserName != null)
        {
            <div>@ViewBag.DisplayUserName</div>
            <div><a id="btnSignOut" href="@Url.Action("Logout","Accounts",new { Area="Admin"})">Log out</a></div>
        }
        else
        {
            <div><a href="@Url.Action("Register","Accounts",new { Area="Admin"})">Register</a></div>
            <div><a href="@Url.Action("Login","Accounts",new { Area="Admin"}) ">Sign in</a></div>
        }
    }
</div>