MobileStore/Controllers/LayoutController.cs
using MobileStore.Common;
using Models.EF;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobileStore.Controllers
{
    public class LayoutController: Controller
    {
        private MobileStoreContext db = new MobileStoreContext();

        public PartialViewResult HeaderCart()
        {
            List<ShoppingCartItemBrowser> list = null;
            if (Session["shoppingcart"] == null)
            {

                list = new List<ShoppingCartItemBrowser>();
                ViewBag.CountItem = 0;
                ViewBag.SumMoney = 0;
            }
            else
            {

                list = (List<ShoppingCartItemBrowser>)Session["shoppingcart"];
                int countItem = 0;
                decimal sumMoney = 0;
                foreach (var item in list)
                {
                    countItem+=1*item.Quantiny;
                    var price = item.Price.GetValueOrDefault();
                    sumMoney += price * item.Quantiny;
                }
                ViewBag.CountItem = countItem;
                ViewBag.SumMoney = sumMoney;
            }
            return PartialView("_HeaderCart");
        }
        public PartialViewResult CategoryMenu()
        {
            //create a listCategoriesTemp
            var listCategoriesTemp = new List<Categories>();
            var Categories = new Categories();
            //star product type id with x=1
            int x = 1;
            Categories.ProductTypeName = db.ProductTypes.Where(m => m.ProductTypeId == x).Select(m => m.ProductTypeName).SingleOrDefault();
            //create a list with product type id asc
            var listProduct = db.Products.OrderBy(m=>m.BrandTypeId).OrderBy(m => m.ProductTypeId);

            List<string> listS1 = new List<string>();
            foreach (var item in listProduct)
            {
                if (item.ProductTypeId == x)
                {
                    listS1.Add(item.BrandType.BrandName);
                }
                else
                {
                    Categories.ListBrandName = listS1;
                    listCategoriesTemp.Add(Categories);
                    x++;
                    Categories = new Categories();
                    Categories.ProductTypeName = db.ProductTypes.Where(m => m.ProductTypeId == x).Select(m => m.ProductTypeName).SingleOrDefault();
                    listS1 = new List<string>();
                    listS1.Add(item.BrandType.BrandName);
                }
            }
            Categories.ListBrandName = listS1;
            listCategoriesTemp.Add(Categories);

            //create listCategories by listCategoriesTemp distinc and brand name asc
            var listCategories = new List<Categories>();
            foreach (var item in listCategoriesTemp)
            {
                Categories = new Categories();
                Categories.ProductTypeName = item.ProductTypeName;
                Categories.ListBrandName = item.ListBrandName.Distinct().ToList();
                listCategories.Add(Categories);
            }

            ViewBag.Categories = listCategories;
            return PartialView("_Categories");
        }

        public PartialViewResult ProductTypeMenu()
        {
            ViewBag.ProductType = db.ProductTypes.Select(m => m.ProductTypeName);
            return PartialView("_ProductType");
        }

        public PartialViewResult AllColorProductMenu(string typeProduct)
        {
            string tbProductType = "Product" + typeProduct;
            ViewBag.AllColorProduct = db.ProductPortableDevices.Select(m => m.Color).Union(db.ProductAccessories.Select(m=>m.Color).Distinct());
            return PartialView("_AllColorProduct");
        }

        public PartialViewResult RecentlyView()
        {
            return PartialView("_RecentlyView");
        }

        public PartialViewResult BranchSlider()
        {
            
            return PartialView("_BranchSlider");
        }

        public PartialViewResult TopbarUser()
        {
            var sessionUser = (LoginModelDisplay)Session["USER_SESSION"];
            if (sessionUser != null)
            {
                ViewBag.DisplayUserName = sessionUser.MemberName;
            }
            return PartialView("_TopbarUser");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);

        }
    }
}

MobileStore/Controllers/ProductInformationPageController.cs
using Models.ViewModels;
using Models.EF;
using Models.Bus;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobileStore.Controllers
{
    public class ProductInformationPageController : Controller
    {
        private MobileStoreContext db = new MobileStoreContext();
        // GET: ProductInformation
        public ActionResult Index(int productTypeId, int productId, int? currentProductDetailId,int? ram, int? memory,string color)
        {
            FormatBus format = new FormatBus();
            ViewBag.ProductTypeId = productTypeId;
            ViewBag.ProductId = productId;

            ViewBag.ProductType = db.ProductTypes.Where(m => m.ProductTypeId == productTypeId).Select(m => m.ProductTypeName).FirstOrDefault();
            //Use this for view index
            ViewBag.ProductName = db.Products.Where(m => m.ProductId == productId).Select(m => m.ProductName).FirstOrDefault();

            //Find ProductId version by memory-ram-color
            if (currentProductDetailId == null)
            {
                if (ViewBag.ProductType == "Smartphone")
                {
                    ViewBag.CurrentProductDetailId = db.ProductPortableDevices.Where(m => m.ProductId == productId && m.RamSize == ram && m.MemorySize == memory && m.Color == color).Select(m => m.ProductPortableDeviceId).FirstOrDefault();
                }
                else if (ViewBag.ProductType == "Accessory")
                {
                    ViewBag.CurrentProductDetailId = db.ProductAccessories.Where(m => m.ProductId == productId && m.Color == color).Select(m => m.ProductAccessoryId).FirstOrDefault();
                }
            }
            else
            {
                ViewBag.CurrentProductDetailId = currentProductDetailId;
            }


            //Filter list All of version in product
            var productInformationList = new List<ProductInformation>();
            if (ViewBag.ProductType == "Smartphone")
            {
                var productSmartphoneList = db.ProductPortableDevices.Where(m => m.ProductId == productId).ToList();
                foreach (var item in productSmartphoneList)
                {
                    productInformationList.Add(new ProductInformation { ProductDetailId = item.ProductPortableDeviceId, ProductId = item.ProductId, Color = item.Color, Price = item.Price, Quantiny = item.Quantiny, FileImage = item.FileImage, Display = item.Display, MemorySize = item.MemorySize, RamSize = item.RamSize });

                    //This is find properties for Current Product
                    if (item.ProductPortableDeviceId == ViewBag.CurrentProductDetailId)
                    {
                        ViewBag.CurrentProductColor = item.Color;
                        ViewBag.CurrentProductRam = item.RamSize;
                        ViewBag.CurrentProductMemory = item.MemorySize;
                        ViewBag.CurrentProductQuantity = item.Quantiny;
                        ViewBag.CurrentProductPrice = item.Price;
                    }
                }
            }
            else if (ViewBag.ProductType == "Accessory")
            {
                var productAccessoryList = db.ProductAccessories.Where(m => m.ProductId == productId).ToList();
                foreach (var item in productAccessoryList)
                {
                    productInformationList.Add(new ProductInformation { ProductDetailId = item.ProductAccessoryId, ProductId = item.ProductId, Color = item.Color, FileImage = item.ImageFile, Quantiny = item.Quantiny });

                    //This is find properties for Current Product
                    if (item.ProductAccessoryId == ViewBag.CurrentProductDetailId)
                    {
                        ViewBag.CurrentProductColor = item.Color;
                        ViewBag.CurrentProductQuantity = item.Quantiny;
                        ViewBag.CurrentProductPrice = item.Price;
                    }
                }

            }
            ViewBag.ColorList = productInformationList.Select(m=>m.Color).Distinct();

            if (ViewBag.ProductType == "Smartphone")
            {
                //Filter versiom distinc have model by ram-memory
                ViewBag.ProductVersionList = from c in productInformationList
                                             group c by new
                                             {
                                                 c.RamSize,
                                                 c.MemorySize
                                             } into grp
                                             select grp.First();

            }
                
            ViewBag.FileImage1 = "/Assets/user/images/" + ViewBag.ProductType + "/" + productId + "-" + ViewBag.CurrentProductColor + "-1" + ".jpg";
            ViewBag.FileImage2 = "/Assets/user/images/" + ViewBag.ProductType + "/" + productId + "-" + ViewBag.CurrentProductColor + "-2" + ".jpg";
            ViewBag.FileImage3 = "/Assets/user/images/" + ViewBag.ProductType + "/" + productId + "-" + ViewBag.CurrentProductColor + "-3" + ".jpg";

            ViewBag.QuantityPrdOrd = null;

            return View(productInformationList);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MobileStore/Controllers/ShopPageController.cs
using Models.ViewModels;
using Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobileStore.Controllers
{
    public class ShopPageController : Controller
    {
        private MobileStoreContext db = new MobileStoreContext();
        // GET: ShopPage
        public ActionResult Index(string productType, string sortOrder,string brand, string currentFilter, string searchString, int? page)
        {
            

            
            int productTypeId = db.ProductTypes.Where(m => m.ProductTypeName == productType).Select(m=>m.ProductTypeId).FirstOrDefault();
            ViewBag.ProductTypeName = productType;
            ViewBag.ProductTypeId = productTypeId;

            List<ProductShop> listPrd= new List<ProductShop>();

            //--Create a list to show Product Shop List
            if (productType != null)
            {
                foreach (var item in db.Products.Where(m => m.ProductTypeId == productTypeId))
                {

                    var prdId = item.ProductId ;
                    ProductShop productShop = new ProductShop();
                    Nullable<decimal> PriceCheapestType = Decimal.MaxValue;
                    int count = 0;

                    //Find branch cheapest in Product to show page shop, Sale marketting
                    if (productType == "Smartphone")
                    {
                        //Search in PortableDevice by product id
                        foreach (var item1 in db.ProductPortableDevices.Where(m => m.ProductId == prdId))
                        {
                            if (item1.Price < PriceCheapestType)
                            {
                                PriceCheapestType = item1.Price;
                            }
                            //Check Quantiny this product to show nofication
                            count += item1.Quantiny;
                        }
                    }
                    else if (productType == "Accessory")
                    {
                        //Search in AccessoryDevice by product id
                            foreach (var item1 in db.ProductAccessories.Where(m => m.ProductId == prdId))
                            {
                                if (item1.Price < PriceCheapestType)
                                {
                                    PriceCheapestType = item1.Price;
                                }
                                count += item1.Quantiny;
                            }
                            
                    }

                    //Assign variable Price Cheapest branch
                    if (productType == "Smartphone")
                    {
                        //Search in PortableDevice by product id
                        foreach (var item1 in db.ProductPortableDevices.Where(m => m.ProductId == prdId))
                        {
                            if (item1.Price == PriceCheapestType)
                            {
                                productShop.CheapestProductId = item1.ProductPortableDeviceId;
                            }
                        }
                    }
                    else if (productType == "Accessory")
                    {
                        //Search in AccessoryDevice by product id
                            foreach (var item1 in db.ProductAccessories.Where(m => m.ProductId == prdId))
                            {
                                if (item1.Price == PriceCheapestType)
                                {
                                productShop.CheapestProductId = item1.ProductAccessoryId;
                                }
                            }
                    }

                    productShop.ProductId = prdId;
                    productShop.ProductName = item.ProductName;
                    productShop.RealeaseDate = item.RealeaseDate;
                    productShop.FileImage = item.FileImage;
                    productShop.PriceCheapestType = PriceCheapestType;
                    productShop.Brand = db.BrandTypes.Where(m=>m.BrandTypeId==item.BrandTypeId).Select(m=>m.BrandName).FirstOrDefault();
                    if (count == 0)
                    {
                        productShop.Stocking = false;
                    }
                    listPrd.Add(productShop);
                }
            }
            //----------------------------------------

            ViewBag.CountProduct = listPrd.Count();
            ViewBag.ProductType = productType;
            ViewBag.BrandList = listPrd.Select(m => m.Brand).Distinct();

            //Paging, sorting part
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                listPrd = listPrd.Where(s => s.ProductName.Contains(searchString)).ToList();
            }

            if (!String.IsNullOrEmpty(brand))
            {
                listPrd = listPrd.Where(m => m.Brand == brand).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    listPrd = listPrd.OrderByDescending(s => s.ProductName).ToList();
                    break;
                case "Date":
                    listPrd = listPrd.OrderBy(s => s.RealeaseDate).ToList();
                    break;
                case "date_desc":
                    listPrd = listPrd.OrderByDescending(s => s.RealeaseDate).ToList();
                    break;
                default:
                    listPrd = listPrd.OrderBy(s => s.ProductName).ToList();
                    break;
            }
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(listPrd.ToPagedList(pageNumber, pageSize));
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MobileStore/Views/ShopPage/Index.cshtml
@model PagedList.IPagedList<Models.ViewModels.ProductShop>
@using PagedList.Mvc;
@using Models.Bus
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Home -->

<div class="home">
    <div class="home_background parallax-window" data-parallax="scroll" data-image-src="/Assets/user/images/shop_background.jpg"></div>
    <div class="home_overlay"></div>
    <div class="home_content d-flex flex-column align-items-center justify-content-center">
        <h2 class="home_title">@ViewBag.ProductType</h2>
    </div>
</div>

<!-- Shop -->

<div class="shop">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">

                <!-- Shop Sidebar -->
                <div class="shop_sidebar">
                    <div class="sidebar_section">
                        <div class="sidebar_title">Categories</div>
                        <ul class="sidebar_categories">
                            @{Html.RenderAction("ProductTypeMenu", "Layout");}
                        </ul>
                    </div>

                    <div class="sidebar_section filter_by_section">
                        <div class="sidebar_title">Filter By</div>
                        <div class="sidebar_subtitle">Price</div>
                        <div class="filter_price">
                            <div id="slider-range" class="slider_range"></div>
                            <p>Range: </p>
                            <p><input type="text" id="amount" class="amount" readonly style="border:0; font-weight:bold;"></p>
                        </div>
                    </div>
                    <div class="sidebar_section">
                        <div class="sidebar_subtitle color_subtitle">Color</div>
                        <ul class="colors_list">
                            @{Html.RenderAction("AllColorProductMenu", "Layout");}
                        </ul>
                    </div>
                    <div class="sidebar_section">
                        <div class="sidebar_subtitle brands_subtitle">Brands</div>
                        <ul class="brands_list">
                            @foreach (var item in ViewBag.BrandList)
                            {
                                <li class="brand"><a href="@Url.Action("Index","ShopPage",new { productType=ViewBag.ProductTypeName,brand=item})">@item</a></li>
                            }
                        </ul>
                    </div>
                </div>

            </div>

            <div class="col-lg-9">

                <!-- Shop Content -->

                <div class="shop_content">
                    <div class="shop_bar clearfix">
                        <div class="shop_product_count"><span>@ViewBag.CountProduct</span> products found</div>
                        <div class="shop_sorting">
                            <span>Sort by:</span>
                            <ul>
                                <li>
                                    <span class="sorting_text">None<i class="fas fa-chevron-down"></span></i>
                                    <ul>
                                        <li class="shop_sorting_button" data-isotope-option='{ "sortBy": "original-order" }'>None</li>
                                        <li class="shop_sorting_button">@Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, productType = ViewBag.ProductType })</li>
                                        <li class="shop_sorting_button">@Html.ActionLink("Date", "Index", new { sortOrder = ViewBag.DateSortParm, productType = ViewBag.ProductType })</li>
                                        <li class="shop_sorting_button" data-isotope-option='{ "sortBy": "price" }'>price</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        @using (Html.BeginForm("Index", "ShopPage", FormMethod.Get, new { style = "float:right; margin-right:22px" }))
                        {
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                        }
                    </div>



                    <div class="product_grid">
                        <div class="product_grid_border"></div>
                        @foreach (var item in Model)
                        {
                            <a href="@Url.Action("Index","ProductInformationPage",new { productTypeId=ViewBag.ProductTypeId,productId=item.ProductId,currentProductDetailId=item.CheapestProductId})">
                                <!-- Product Item -->
                                <div class="product_item is_new">
                                    <div class="product_border"></div>
                                    <div class="product_image d-flex flex-column align-items-center justify-content-center"><img src="@item.FileImage" alt=""></div>
                                    <div class="product_content">
                                        <div class="product_price">
                                            @{
                                                FormatBus format = new FormatBus();
                                                var priceToTalDisplay = format.FormatDecimalDisplay(@item.PriceCheapestType);
                                                @priceToTalDisplay
                                            }
                                        </div>
                                        <div class="product_name"><div><a href="#" tabindex="0">@item.ProductName</a></div></div>
                                    </div>
                                    <div class="product_fav"><i class="fas fa-heart"></i></div>
                                    <ul class="product_marks">
                                        <li class="product_mark product_discount">-25%</li>
                                        <li class="product_mark product_new">new</li>
                                    </ul>
                                </div>
                            </a>
                        }


                    </div>

                    <!-- Shop Page Navigation -->

                    <div class="shop_page_nav d-flex flex-row">
                        @*<ul class="page_nav d-flex flex-row">
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">...</a></li>
                                <li><a href="#">21</a></li>
                            </ul>*@
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, productType = ViewBag.ProductType }))
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

@{Html.RenderAction("RecentlyView", "Layout");}
@{Html.RenderAction("BranchSlider", "Layout");}

@section Plugin1
{
    <link rel="stylesheet" type="text/css" href="/Assets/user/styles/bootstrap4/bootstrap.min.css">
    <link href="/Assets/user/plugins/fontawesome-free-5.0.1/css/fontawesome-all.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/Assets/user/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="/Assets/user/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="/Assets/user/plugins/OwlCarousel2-2.2.1/animate.css">
    <link rel="stylesheet" type="text/css" href="/Assets/user/plugins/jquery-ui-1.12.1.custom/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="/Assets/user/styles/shop_styles.css">
    <link rel="stylesheet" type="text/css" href="/Assets/user/styles/shop_responsive.css">
}

@section Plugin2
{
    <script src="/Assets/user/js/jquery-3.3.1.min.js"></script>
    <script src="/Assets/user/styles/bootstrap4/popper.js"></script>
    <script src="/Assets/user/styles/bootstrap4/bootstrap.min.js"></script>
    <script src="/Assets/user/plugins/greensock/TweenMax.min.js"></script>
    <script src="/Assets/user/plugins/greensock/TimelineMax.min.js"></script>
    <script src="/Assets/user/plugins/scrollmagic/ScrollMagic.min.js"></script>
    <script src="/Assets/user/plugins/greensock/animation.gsap.min.js"></script>
    <script src="/Assets/user/plugins/greensock/ScrollToPlugin.min.js"></script>
    <script src="/Assets/user/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
    <script src="/Assets/user/plugins/easing/easing.js"></script>
    <script src="/Assets/user/plugins/Isotope/isotope.pkgd.min.js"></script>
    <script src="/Assets/user/plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
    <script src="/Assets/user/plugins/parallax-js-master/parallax.min.js"></script>
    <script src="/Assets/user/js/shop_custom.js"></script>
}