MobileStore/Areas/Admin/Controllers/AccountsController.cs
using Facebook;
using MobileStore.Common;
using Models.Bus;
using Models.EF;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace MobileStore.Areas.Admin.Controllers
{
    public class AccountsController : Controller
    {
        private MobileStoreContext db = new MobileStoreContext();
        public ActionResult Login()
        {
            ViewBag.GGSigninClientContent = ConfigurationManager.AppSettings["GgAppId"].ToString();
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            ViewBag.GGSigninClientContent = ConfigurationManager.AppSettings["GgAppId"].ToString();
            if (ModelState.IsValid) {
                var userBus = new UserBus();
                var result = userBus.Login(model.MemberEmail, EncryptorMD5.MD5Hash(model.MemberPassword));

                LoginModelDisplay loginModelDisplay = new LoginModelDisplay();
                loginModelDisplay.MemberAccountId = db.Members.Where(m => m.MemberEmail == model.MemberEmail).Select(m => m.MemberId).SingleOrDefault();
                loginModelDisplay.MemberEmail = model.MemberEmail;
                loginModelDisplay.RememberMe = model.RememberMe;
                loginModelDisplay.MemberName = db.Members.Where(m => m.MemberEmail == model.MemberEmail).Select(m => m.FullName).FirstOrDefault();
                loginModelDisplay.MemberTypeId = result;


                if (result == 1 || result == 2)
                {
                    Session.Remove(CommonConstants.USER_SESSION);
                    Session.Add(CommonConstants.USER_SESSION, loginModelDisplay);
                    return RedirectToAction("Index", "ADHome");
                }
                else if (result == 3)
                {
                    Session.Remove(CommonConstants.USER_SESSION);
                    Session.Add(CommonConstants.USER_SESSION, loginModelDisplay);
                    return RedirectToAction("Index", "Home", new { area = "" });
                }
                else
                {
                    ModelState.AddModelError("LoginCheck", "Đăng nhập không đúng");
                    return View(model);
                }
            }

            return View(model);
        }

        public ActionResult Register()
        {
            ViewBag.GenderTypeId = new SelectList(db.GenderTypes, "GenderTypeId", "GenderName");
            return View();
        }

        [HttpPost]
        public ActionResult Register(RegisterModel registerModel)
        {
            var jsonAuthenticationEmail = (JsonAthenticationEmail)Session["authenticationemail"];
            if (ModelState.IsValid)
            {
                if (registerModel.MemberEmail == jsonAuthenticationEmail.Email & registerModel.CodeAuth == jsonAuthenticationEmail.AuthenticationCode)
                {

                    Session["shoppingcart"] = null;
                    Member member = new Member() { MemberEmail = registerModel.MemberEmail, MemberPassword = EncryptorMD5.MD5Hash(registerModel.MemberPassword), FullName = registerModel.FullName, GenderTypeId = registerModel.GenderTypeId, PhoneNumber = registerModel.PhoneNumber, MemberTypeId = 3, RegDate = System.DateTime.Now };
                    db.Members.Add(member);
                    AddressMember addressMember = new AddressMember() { AddressMemberName = registerModel.HomeAddress, MemberId = member.MemberId, PriorityStatus = 1 };
                    db.AddressMembers.Add(addressMember);
                    db.SaveChanges();

                    LoginModelDisplay loginModelDisplay = new LoginModelDisplay();
                    loginModelDisplay.MemberAccountId = member.MemberId;
                    loginModelDisplay.MemberEmail = member.MemberEmail;
                    //loginModelDisplay.RememberMe =  ;
                    loginModelDisplay.MemberName = member.FullName;
                    loginModelDisplay.MemberTypeId = 3;

                    Session.Remove(CommonConstants.USER_SESSION);
                    Session.Add(CommonConstants.USER_SESSION, loginModelDisplay);

                    return RedirectToAction("Index", "Home", new { area = "" });
                }
                else
                {
                    ModelState.AddModelError("RegisterCheck", "Mã xác thực không hợp lệ");
                    return View(registerModel);
                }
            }
            
            ViewBag.GenderTypeId = new SelectList(db.GenderTypes, "GenderTypeId", "GenderName");
            return View(registerModel);
        }

        public JsonResult GetAuthenticationInEmail(string Email)
        {
            var findThisEmail = db.Members.Where(m => m.MemberEmail == Email).Select(m=>m.MemberEmail).FirstOrDefault();

            if (findThisEmail==null)
            {
                Session["authenticationemail"] = null;
                int authCode = new Random().Next(1000, 9999);
                JsonAthenticationEmail jsonAuthenticationEmail = new JsonAthenticationEmail();
                jsonAuthenticationEmail.Email = Email;
                jsonAuthenticationEmail.AuthenticationCode = authCode.ToString();
                Session["authenticationemail"] = jsonAuthenticationEmail;

                MailHelper.SendMailAuthentication(Email, "Ma xac thuc tu Trung Store", authCode.ToString());

                return Json(new { status=true});
            }
            else
                return Json(new {  status = false});
        }
            

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }

        public ActionResult LoginFB()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secrect = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });
            return Redirect(loginUrl.AbsoluteUri);
        }

        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });
            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
                // Get the user's information, like email, first name, middle name etc
                dynamic me = fb.Get("me?field=email,id,name");
                string emailFB = me.email;
                string nameFB = me.name;
                string idFB = me.id;

                //Create member account add database
                var memberAccount = new Member();
                memberAccount.MemberEmail = emailFB;
                memberAccount.MemberTypeId = 2;
                memberAccount.FullName = nameFB;
                memberAccount.MemberFacebookId = idFB;

                var resultInsertFb = new UserBus().InsertUserFb(memberAccount);

                //Add Session to display view
                LoginModelDisplay loginModelDisplay = new LoginModelDisplay();
                loginModelDisplay.MemberAccountId = resultInsertFb;
                loginModelDisplay.MemberEmail = memberAccount.MemberEmail;
                loginModelDisplay.MemberName = memberAccount.FullName;
                loginModelDisplay.MemberTypeId = 2;

                Session.Remove(CommonConstants.USER_SESSION);
                Session.Add(CommonConstants.USER_SESSION, loginModelDisplay);

            }
            return Redirect("/");
        }

        public JsonResult LoginGoogle(string googleACModel)
        {
            var accountSocialsList = new JavaScriptSerializer().Deserialize<List<AccountSocial>>(googleACModel);
            var accountSocials = accountSocialsList.FirstOrDefault();
            var memberAccount = new Member();
            memberAccount.MemberEmail = accountSocials.Email;
            memberAccount.MemberTypeId = 2;
            memberAccount.FullName = accountSocials.FullName;
            memberAccount.MemberGoogleId = accountSocials.AccountId;
            var resultInsertGg = new UserBus().InsertUserGg(memberAccount);

            //Add Session to display view
            LoginModelDisplay loginModelDisplay = new LoginModelDisplay();
            loginModelDisplay.MemberAccountId = resultInsertGg;
            loginModelDisplay.MemberEmail = memberAccount.MemberEmail;
            loginModelDisplay.MemberName = memberAccount.FullName;
            loginModelDisplay.MemberTypeId = 2;

            Session.Remove(CommonConstants.USER_SESSION);
            Session.Add(CommonConstants.USER_SESSION, loginModelDisplay);



            return Json(new { status = true });
        }



        public ActionResult Logout()
        {
            Session.Remove(CommonConstants.USER_SESSION);
            return RedirectToAction("Index", "Home", new { area = "" });
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

MobileStore/Areas/Admin/Views/Accounts/Login.cshtml
@model Models.ViewModels.LoginModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Star Admin Free Bootstrap Admin Dashboard Template</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/Assets/admin/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/Assets/admin/vendors/iconfonts/puse-icons-feather/feather.css">
    <link rel="stylesheet" href="/Assets/admin/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="/Assets/admin/vendors/css/vendor.bundle.addons.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="/Assets/admin/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="/Assets/admin/images/favicon.png" />

    <!-- google log -->
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content=@ViewBag.GGSigninClientContent>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <!---------------->

</head>

<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
            <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
                <div class="row w-100">
                    <div class="col-lg-4 mx-auto">
                        <div id="form-login" class="auto-form-wrapper">
                            @using (Html.BeginForm("Login", "Accounts", FormMethod.Post))
                            {
                                <div class="form-group">
                                    <label class="label">Username</label>
                                    <div class="input-group">

                                        @Html.TextBoxFor(model => model.MemberEmail, new { @class = "form-control", @placeholder = "EmailUser", @autofocus = "autofocus", @type = "email" })
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <p style="color:red;float:right">@Html.ValidationMessageFor(model => model.MemberEmail)</p>
                                </div>
                                <div class="form-group">
                                    <label class="label">Password</label>
                                    <div class="input-group">
                                        @Html.PasswordFor(model => model.MemberPassword, new { @class = "form-control", @placeholder = "*********" })
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <p style="color:red;float:right">@Html.ValidationMessageFor(model => model.MemberPassword)</p>
                                </div>
                                <p style="color:red;float:right">@Html.ValidationMessage("LoginCheck")</p>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary submit-btn btn-block">Login</button>
                                </div>
                                <div class="form-group d-flex justify-content-between">
                                    <div class="form-check form-check-flat mt-0">
                                        <label class="form-check-label">
                                            @Html.CheckBoxFor(model => model.RememberMe, new { @class = "form-check-input" }) Keep me signed in
                                        </label>
                                    </div>
                                    <a href="#" class="text-small forgot-password text-black">Forgot Password</a>
                                </div>
                                <div class="form-group">
                                    <div style="float:right" class="g-signin2" data-onsuccess="onSignIn"></div>
                                    <a href="/Admin/Accounts/LoginFB">
                                        <img class="mr-3" src="~/Assets/admin/images/file-icon/icon-facebook.png" style="width:7%" alt="">
                                    </a>
                                </div>
                                <div class="text-block text-center my-3">
                                    <span class="text-small font-weight-semibold">Not a member ?</span>
                                    <a href="register.html" class="text-black text-small">Create new account</a>
                                </div>
                            }
                        </div>
                        <div id="form-login-success" class="auto-form-wrapper">
                            <a href="/">Come back home stay</a>
                        </div>
                        <ul class="auth-footer">
                            <li>
                                <a href="#">Conditions</a>
                            </li>
                            <li>
                                <a href="#">Help</a>
                            </li>
                            <li>
                                <a href="#">Terms</a>
                            </li>
                        </ul>
                        <p class="footer-text text-center">copyright © 2018 Bootstrapdash. All rights reserved.</p>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/Assets/admin/vendors/js/vendor.bundle.base.js"></script>
    <script src="~/Assets/admin/vendors/js/vendor.bundle.addons.js"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="~/Assets/admin/js/off-canvas.js"></script>
    <script src="~/Assets/admin/js/misc.js"></script>
    <!-- endinject -->

    <script>
        function onSignIn(googleUser) {
            // Useful data for your client-side scripts:
            var profile = googleUser.getBasicProfile();
            console.log("ID: " + profile.getId()); // Don't send this directly to your server!
            console.log('Full Name: ' + profile.getName());
            console.log('Given Name: ' + profile.getGivenName());
            console.log('Family Name: ' + profile.getFamilyName());
            console.log("Image URL: " + profile.getImageUrl());
            console.log("Email: " + profile.getEmail());

            // The ID token you need to pass to your backend:
            var id_token = googleUser.getAuthResponse().id_token;
            console.log("ID Token: " + id_token);

            var googleAC = [];
            googleAC.push({
                AccountId: profile.getId(),
                FullName: profile.getName(),
                Email: profile.getEmail(),
                IdToken: googleUser.getAuthResponse().id_token
            });
            $.ajax({
                url: '/Admin/Accounts/LoginGoogle',
                data: { googleACModel: JSON.stringify(googleAC) },
                dataType: 'json',
                type: 'POST',
                success: function (data) {
                    if (data.status == true) {
                        alert('Login Success');
                        window.location.href = "/";
                    }
                }
            });
        }
    </script>
</body>

</html>

MobileStore/Areas/Admin/Views/Accounts/Register.cshtml
@model Models.ViewModels.RegisterModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Star Admin Free Bootstrap Admin Dashboard Template</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/Assets/admin/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/Assets/admin/vendors/iconfonts/puse-icons-feather/feather.css">
    <link rel="stylesheet" href="/Assets/admin/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="/Assets/admin/vendors/css/vendor.bundle.addons.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="/Assets/admin/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="/Assets/admin/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
            <div class="content-wrapper d-flex align-items-center auth register-bg-1 theme-one">
                <div class="row w-100">
                    <div class="col-lg-4 mx-auto">
                        <h2 class="text-center mb-4">Register</h2>
                        <div class="auto-form-wrapper">
                            @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "registerForm" }))
                            {
                                @Html.AntiForgeryToken();
                                <div class="form-group">
                                    <div class="input-group">
                                        @Html.EditorFor(model => model.MemberEmail, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email", @type = "email" } })
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <p style="color:red;float:right">@Html.ValidationMessageFor(model => model.MemberEmail)</p>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        @Html.PasswordFor(model => model.MemberPassword, new { @class = "form-control", @placeholder = "Password" })
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <p style="color:red;float:right">@Html.ValidationMessageFor(model => model.MemberPassword)</p>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="password" name="re_password" class="form-control" placeholder="Confirm Password">
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Full Name" } })
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <p style="color:red;float:right">@Html.ValidationMessageFor(model => model.FullName)</p>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-3 col-form-label">Giới tính</label>
                                    <div class="col-sm-9">
                                        @Html.DropDownList("GenderTypeId", null, htmlAttributes: new { @class = "form-control" })
                                    </div>

                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        @Html.EditorFor(model => model.HomeAddress, new { htmlAttributes = new { @class = "form-control", @placeholder = "Home Address" } })
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <p style="color:red;float:right">@Html.ValidationMessageFor(model => model.HomeAddress)</p>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @placeholder = "Phone Number", @type = "number" } })
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <i class="mdi mdi-check-circle-outline"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <p style="color:red;float:right">@Html.ValidationMessageFor(model => model.PhoneNumber)</p>
                                </div>

                                <div class="form-group">
                                    <div class="input-group">
                                        @Html.EditorFor(model => model.CodeAuth, new { htmlAttributes = new { @class = "form-control", @placeholder = "Mã xác thực" } })
                                        <div class="input-group-append">
                                                <button id="btnGetAuthCode" class="btn btn-success" type="button">Lấy mã xác thực</button>
                                        </div>
                                    </div>
                                    <p style="color:red;float:right">@Html.ValidationMessageFor(model => model.CodeAuth)</p>
                                </div>

                                <div class="form-group d-flex justify-content-center">

                                    <div class="form-check form-check-flat mt-0">
                                        <label class="form-check-label">
                                            <input type="checkbox" class="form-check-input" checked> I agree to the terms
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary submit-btn btn-block">Register</button>
                                </div>
                                <div class="text-block text-center my-3">
                                    <span class="text-small font-weight-semibold">Already have and account ?</span>
                                    <a href="@Url.Action("Login","Accounts",new { Area="Admin"})" class="text-black text-small">Login</a>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>




    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="/Assets/admin/vendors/js/vendor.bundle.base.js"></script>
    <script src="/Assets/admin/vendors/js/vendor.bundle.addons.js"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="/Assets/admin/js/off-canvas.js"></script>
    <script src="/Assets/admin/js/misc.js"></script>
    <!-- endinject -->

    <script>
        $('#btnGetAuthCode').off('click').on('click', function () {
            alert("Đang kiểm tra...")
            var memberEmail = document.getElementById('MemberEmail').value;
            if (memberEmail) {
                $.ajax({
                    url: '/Accounts/GetAuthenticationInEmail',
                    data: { Email: memberEmail },
                    dataType: 'json',
                    type: 'POST',
                    success: function (res) {
                        if (res.status == true) {
                            alert("Mã xác thực đã được gửi vào email  " + memberEmail)
                        }
                        else {
                            alert("Email " + memberEmail+ " đã tồn tại" )
                        }
                    }
                });
            }
            else {
                alert("Ban chua nhap email")
            }
            
        });
    </script>


</body>
</html>